AllCops:
  TargetRubyVersion: 2.5.1
LineLength:
  Max: 120
ClassLength:
  Exclude:
    - app/serializers/es/sku_serializer.rb
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/RescueStandardError:
  EnforcedStyle: implicit
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'namespace']
  Exclude:
    - spec/serializers/es/sku_serializer_spec.rb
    - spec/services/serializers/decorated_skus_serializer_service_spec.rb
    - spec/support/shared_examples*
Rails:
  Enabled: true

Rails/InverseOf:
  Exclude:
  # do not clutter up main models with associations to inbound or external tables
    - app/models/concerns/inbound/okl/*
    - app/models/concerns/external/xpdm/*
    - app/models/inbound/okl/*
    - app/models/concerns/inbound/common_concept_foreign_keys.rb
    - app/models/external/xpdm/*
Naming/MemoizedInstanceVariableName:
  Exclude:
    - app/serializers/product_serializer.rb
    - app/services/serializers/decorated_skus_serializer_service.rb
#@TODO END of new rubocops
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - test/**/*
    - Gemfile
    - Guardfile
    - Rakefile
    - vendor/**/*

inherit_from: .rubocop_todo.yml
