pg_defaults: &pg_defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: universal_catalog
  username: dev
  password: dev

docker: &docker
  <<: *pg_defaults
  host: db_postgres
  port: 5432

development:
  <<: *pg_defaults
  database: universal_catalog
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: "<%= ENV.fetch('DATABASE_PASSWORD') %>"

test:
  <<: *pg_defaults
  database: universal_catalog_test
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: "<%= ENV.fetch('DATABASE_PASSWORD') %>"

production:
  <<: *pg_defaults
  database: universal_catalog
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: "<%= ENV.fetch('DATABASE_PASSWORD') %>"

external_pdm_development: &external_development
  adapter: oracle_enhanced
  statement_limit: 300
  schema: 'PDMADMIN'
#  url: "<%= ENV.fetch('PDMADMIN_URL', 'no-oracle-present://lalala') %>"
  username: "<%= ENV.fetch('PDMADMIN_USER', '') %>"
  password: "<%= ENV.fetch('PDMADMIN_PASSWORD', '') %>"
  database: "<%= ENV.fetch('PDMADMIN_DB', '') %>"

external_pdm_test: &external_pdm_test
  adapter: oracle_enhanced
  statement_limit: 300
  schema: 'TESTUSER'
  url: "oracle-enhanced://TESTUSER:test@localhost:1521/XE"

external_ecom_test:
  <<: *external_pdm_test
  schema: 'ECOMADMIN'
  url: "oracle-enhanced://ECOMADMIN:test@localhost:1521/XE"
