TransformationJob:
  class: 'Transform::TransformationJob'
  cron: '*/15 * * * *'
  args: 'OKL'
  queue: transform
  description: 'Transforms OKL data from inbound tables into polished tables - note this is secondary because they are usually kicked off as messages are received.'
