redis_defaults: &redis_defaults
  host: <%= ENV.fetch('REDIS_HOST') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>

default_settings: &defaults
  product_catalog_url: <%= ENV.fetch('BBB_CATALOG_WEB_FRONTEND', 'https://pc.bbby.io') %>
  enable_pdm_connection: <%= 'false' != ENV.fetch('ENABLE_PDM_CONNECTION', 'false') %>
  solr:
    enabled: <%= ENV.fetch('SOLR_ENABLED', 'true') == 'true' %>
    endpoint: <%= ENV.fetch('SOLR_ENDPOINT') %>
  redis:
    mutex:
      <<: *redis_defaults
      db: <%= ENV.fetch('REDIS_MUTEX_DB', 1) %>
    resque:
      <<: *redis_defaults
      db: <%= ENV.fetch('REDIS_RESQUE_DB', 2) %>
  job_lock_ttl_in_seconds:
    inbound_transformation_job__okl: <%= ENV.fetch('INBOUND_TRANSFORM_JOB_LOCK_TTL_OKL', 20 * 60) %>
    inbound_transformation_job__JDA: <%= ENV.fetch('INBOUND_TRANSFORM_JOB_LOCK_TTL_JDA', 40 * 60) %>
    inbound_transformation_job__SALES: <%= ENV.fetch('INBOUND_TRANSFORM_JOB_LOCK_TTL_SALES', 240 * 60) %>
    inbound_transformation_job__DW: <%= ENV.fetch('INBOUND_TRANSFORM_JOB_LOCK_TTL_DW', 240 * 60) %>
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
