redis_defaults: &redis_defaults
  host: <%= ENV.fetch('REDIS_HOST') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>

default_settings: &defaults
  enable_pdm_connection: <%= 'false' != ENV.fetch('ENABLE_PDM_CONNECTION', 'false') %>
  solr:
    enabled: <%= ENV.fetch('SOLR_ENABLED', 'true') == 'true' %>
    endpoint: <%= ENV.fetch('SOLR_ENDPOINT') %>
  redis:
    mutex:
      <<: *redis_defaults
      db: <%= ENV.fetch('REDIS_MUTEX_DB', 1) %>
    resque:
      <<: *redis_defaults
      db: <%= ENV.fetch('REDIS_RESQUE_DB', 2) %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
